#!/bin/sh

# US keyboard layout
setxkbmap -layout "us" -option "ctrl:nocaps" -option "compose:ralt"

xsetroot -cursor_name left_ptr
xset r rate 300 75
xset -b

xrdb -load .Xdefaults

# Wacom Bamboo Pen & Touch configuration
#/home/cgie/wacom-init

$HOME/.gem/ruby/2.0.0/gems/gollum-2.5.2/bin/gollum /repos/labnotes &

# Sync clipboards
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Automatically lock the screen
xautolock &

# Auto-start applications
trayer --edge top --align right --widthtype request --expand true --SetDockType true --SetPartialStrut true --transparent true --alpha 0 --tint 0xfdf6e3 --expand true --heighttype pixel --height 14  --padding 1 &
nitrogen --restore &
xcompmgr &
sleep 120 && dropboxd &

exec xmonad


